name: dbt_workspace_poc_2
version: 1.0.0
config-version: 2
profile: dbt_workspace_poc_2
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  dbt_workspace_poc_2:
    +materialized: view
