dbt_workspace_poc_2:
  target: dev
  outputs:
    dev:
      account: '_' # Put any value here, it will be overwritten by a GitHub repository secret
      database: POC_2_DBT
      schema: dev
      role: ACCOUNTADMIN # Use whichever role has USAGE on the database and schema
      type: snowflake
      warehouse: COMPUTE_WH # Replace with your active warehouse name, e.g., my_wh
      user: '_' # Put any value here, it will be overwritten by a GitHub repository secret
    prod:
      account: '_' # Put any value here, it will be overwritten by a GitHub repository secret
      database: POC_2_DBT_PROD
      schema: dev
      role: ACCOUNTADMIN # Use whichever role has USAGE on the database and schema
      type: snowflake
      warehouse: COMPUTE_WH # Replace with your active warehouse name
      user: '_' # Put any value here, it will be overwritten by a GitHub repository secret
